version: "3.8"

services:

  db:
    build: ./docker/db
    container_name: hostel-db
    ports:
      - "3306:3306"

  app:
    build: ./docker/app
    container_name: hostel-app
    ports:
      - "3000:3000"
    depends_on:
      - db
